### ISSUE TITLE
How to use subfolders as link instead of categories?

### ISSUE THREAD

**Issue by JulianSchoenbaechler** [nliautaud/pico-pages-list#3]
I have following content structure:
- Index file
- Subfolder
  - Index file
  - Another subfolder
    - Index file

Instead of those `<span>` tags, I would like to get links directly to the index files of each subfolder:
- Index file
- [Subfolder index](#)
  - [Another subfolder index](#)

Is this anyhow possible?

**Comment by nliautaud** [comment]
That was a bug, it's supposed to be the default behavior when a subfolder page exists. Should be fixed !

**Comment by JulianSchoenbaechler** [comment]
Nice, but this only works partially:
The subfolders are now always nested under the main folder index tab...

Instead of:

- Index file
- Subfolder index
  - Another subfolder index

I get:
- Index file
  - Subfolder index
    - Another subfolder index

**Comment by nliautaud** [comment]
Hi, could you try with the 3.0 branch ?
https://github.com/nliautaud/pico-pages-list/tree/3.0

The system have been extensively modified. You may want to look at the updated readme.

**Comment by JulianSchoenbaechler** [comment]
It's nice seeing this plugin actively updated!
But I think my problem persists. To reproduce -> my content folder looks like this:
- **content/**
  - index.md
  - 404.md
  - **doc/**
    - index.md
    - **subfolder/**
      - index.md
      - page.md
      - **anothersubfolder/**
        - index.md

I would like to create a navigation for the subfolder **doc/**, so my Twig template looks something like this:
```html
<nav role="navigation">
    {{ (nested_pages | only('doc/')) | navigation }}
</nav>
```
But this won't give me a navigation at all... If I change it to:
```html
<nav role="navigation">
    {{ (nested_pages | only('doc')) | navigation }}
</nav>
```
The navigation looks like this:
- Doc Index
  - Subfolder Index
    - Subfolder Page
    - Another subfolder index

But the `Doc Index` and the `Subfolder Index` should be on the same level.

**Comment by nliautaud** [comment]
Thanks for you help :)

I don't have `Doc Index` on the same level here with your structure. Could you output the page.id's ?

I can reproduce the issue with `only()` though. I did this new version a few hours ago, I had to miss something.

![2017-10-24 15_58_59-home _ pico](https://user-images.githubusercontent.com/761761/31947513-c358979e-b8d4-11e7-951c-65e577f22007.png)  

Note that parenthesis aren't required : `{{ nested_pages | only('doc') | navigation }}` is ok.

**Comment by JulianSchoenbaechler** [comment]
Whoops, you're right. No problem there when using `{{ nested_pages | navigation }}` without `only()`.

**Comment by nliautaud** [comment]
I fixed the logic behind `only()`. Didn't thought this one enough, as it had to behave differently than `exclude` with a nested context : 

![2017-10-24 17_10_40-home _ pico](https://user-images.githubusercontent.com/761761/31951397-47e62b76-b8de-11e7-89d7-ff2c7af0172f.png)

Do you still have the home nesting issue ?

**Comment by JulianSchoenbaechler** [comment]
Well, nice! Fixed that one.
Would it also be possible to get `doc (index)` and `subfolder (index)` on the same level using `only`?

**Comment by nliautaud** [comment]
Great :)

It depends on what you want (nested or not, which childs to show...) : 

```twig
flat
{{ pages | only('doc') | navigation }}

nested with two entry points
{{ nested_pages | only('doc,doc/subfolder') | navigation }}

excluding childs
{{ pages | only('doc,doc/subfolder') | exclude('doc/subfolder/') | navigation }}
```
